DATA_PARAM:
  Bvh: 
    bvh2smplbvh: False
TRAIN_PARAM:
  tag: wav_dtw_mfcc
  motion_extractor:
    use: False
  pretrained_infer: False
  wav_dtw_mfcc:
    noise: True
    ablation: full
    ablation_version: v0 
    frame_based_feats: True
  log_tag: ast_noise_feat
