DATA_PARAM:
  Bvh: 
    bvh2smplbvh: False
TRAIN_PARAM:
  tag: latent_diffusion
  motion_extractor:
    use: False
  pretrained_infer: False
  wav_dtw_mfcc:
    noise: True
    ablation: full 
    ablation_version: v1
    frame_based_feats: True
  log_tag: v1_full_6d_vtex_b32 
  diffusion:
    lmdb_cache: BEAT-cache/2023-10-28_30F_fing_smplx_MOSH_full_v1_feat_based_300
  latent_diffusion:
    smplx_rep: 6D 
    pretrained_ast: wav_dtw_mfcc_20231022-044436_actors
    n_epochs: 12000 
    batch_size: 32 # 16 32 48 56
    half_body: False 
    train_upper_body: False
    skip_trans: False
    vtex_displacement: True
  test:
    emotion_control:
      use: False 
    style_transfer:
      use: False 
    style_Xemo_transfer:
      use: False
    audio_list:
      use: False
  baselines:
    run: False 
